Projeto Aula 8 - MVC/Models/ErrorViewModel.cs
namespace Projeto_Aula_8___MVC.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Projeto Aula 8 - MVC/Models/PastelViewModel.cs
namespace Projeto_Aula_8___MVC.Models;

public class PastelViewModel
{

    public string Recheio { get; private set; }
    public decimal Preco { get; private set; }

    public PastelViewModel(string recheio, decimal preco)
    {
        Recheio = recheio;
        Preco = preco;
    }

}

Projeto Aula 8 - MVC/Controllers/CoxinhaController.cs
using Microsoft.AspNetCore.Mvc;

namespace Projeto_Aula_8___MVC.Controllers;
public class CoxinhaController : Controller
{
	public IActionResult Index()
	{
		return View();
	}

	public IActionResult Pastel()
	{
		return View();
	}
}

Projeto Aula 8 - MVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto_Aula_8___MVC.Models;
using System.Diagnostics;

namespace Projeto_Aula_8___MVC.Controllers;
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Projeto Aula 8 - MVC/Controllers/PastelariaController.cs
using Microsoft.AspNetCore.Mvc;
using Projeto_Aula_8___MVC.Models;

namespace Projeto_Aula_8___MVC.Controllers;
public class PastelariaController : Controller
{
	public IActionResult Index()
	{
		var a = ViewBag.Autenticado;
		var b = ViewData["Nome"];
		var c = TempData["Oito"];

		return View();
	}

	[HttpPost]
	public IActionResult Index(string Recheio)
	{
		var a = ViewBag.Autenticado;
		var b = ViewData["Nome"];
		var c = TempData["Oito"];

		return View();
	}

	public IActionResult Menu()
	{
		var pasteis = new List<PastelViewModel>()
		{
			new PastelViewModel("Queijo", 5.35M),
			new PastelViewModel("Carne", 4.99M),
			new PastelViewModel("Palmito", 6.00M),
			new PastelViewModel("Catupiri", 2.24M),
		};
		return View(pasteis);
	}
}

Projeto Aula 8 - MVC/Views/Coxinha/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

@{
	ViewData["Title"] = "Coxinha";
}

<h1>Coxinha</h1>

Projeto Aula 8 - MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Projeto Aula 8 - MVC/Views/Pastelaria/Index.cshtml
<h1> Seja bem vindo à nossa pastelaria</h1>

<p>
	Lorem ipsum dolor sit amet, consectetur adipiscing elit,
	sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
	Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
	ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit
	esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
</p>

<p>
	Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque
	laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi
	architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
	sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione
	voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit
	amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut
	labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis
	nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi
	consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam
	nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?
</p>


<p>@ViewBag.Autenticado</p>
<p>@ViewData["Nome"]</p>
<p>@TempData["Oito"]</p>

	<form method="post">
		<span> 
			<input type="text" name="rEcHeIo"/>
			<button type="submit" formmethod="post"> Fazer pedido </button> 
		</span>
	</form>

Projeto Aula 8 - MVC/Views/Pastelaria/Menu.cshtml
@model List<PastelViewModel>

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@

<h1>Menu</h1>


<ul>
@foreach (var pastel in Model)
{
    <li> <partial name="_MenuItem" model=pastel/> </li>
}
</ul>

<p>@ViewBag.Autenticado </p>
<p>@ViewData["Nome"]</p>
<p>@TempData["Oito"]</p>

Projeto Aula 8 - MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Projeto_Aula_8___MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Projeto_Aula_8___MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Projeto_Aula_8___MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pastelaria" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pastelaria" asp-action="Menu">Menu</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Projeto_Aula_8___MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Projeto Aula 8 - MVC/Views/Shared/_MenuItem.cshtml
@model PastelViewModel

<span>Pastel de @Model.Recheio: R$@Model.Preco </span>